package com.fastt.inflect

import org.json.JSONArray
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test

/**
 * Pins [PhonemeTokenizer] against fixtures generated by the verified Python pipeline
 * (`scripts/export_android_assets.py`). If eSpeak or the symbol table ever drifts, this
 * fails instead of the app quietly producing wrong audio.
 */
class PhonemeTokenizerTest {

    private fun resource(name: String): String =
        checkNotNull(javaClass.classLoader?.getResourceAsStream(name)) {
            "missing test resource $name - run scripts/export_android_assets.py"
        }.bufferedReader().use { it.readText() }

    private val tokenizer: PhonemeTokenizer by lazy {
        PhonemeTokenizer.fromJson(resource("symbols.json"))
    }

    @Test
    fun `matches python golden tokens`() {
        val fixtures = JSONArray(resource("golden_tokens.json"))
        assertEquals(3, fixtures.length())

        for (i in 0 until fixtures.length()) {
            val fixture = fixtures.getJSONObject(i)
            val expectedJson = fixture.getJSONArray("tokens")
            val expected = LongArray(expectedJson.length()) { expectedJson.getLong(it) }

            val actual = tokenizer.toTokens(fixture.getString("phonemes"))

            assertArrayEquals(fixture.getString("text"), expected, actual)
        }
    }

    @Test
    fun `interleaves blanks around every phoneme`() {
        val tokens = tokenizer.toTokens("ɐ")
        assertArrayEquals(longArrayOf(0, tokens[1], 0), tokens)
    }

    @Test
    fun `rejects symbols outside the table`() {
        assertThrows(IllegalArgumentException::class.java) { tokenizer.toTokens("日") }
    }

    @Test
    fun `demo fixtures phonemize to the golden phoneme strings`() {
        val fixtures = JSONArray(resource("golden_tokens.json"))
        for (i in 0 until fixtures.length()) {
            val fixture = fixtures.getJSONObject(i)
            assertEquals(
                fixture.getString("phonemes"),
                FixturePhonemeSource.DEMO.phonemize(fixture.getString("text")),
            )
        }
    }
}
