#!/usr/bin/env python3
"""Dump the exact tensor contract of duration.onnx and decode.onnx for each variant.

This is the deliverable that the Android/Kotlin side codes against: nothing downstream
should guess input names, dtypes or axis order - it should read docs/TENSOR_CONTRACT.md.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import onnx
import onnxruntime as ort

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from inflect_sandbox.frontend import MODELS_DIR, VARIANTS  # noqa: E402

OUT = ROOT / "docs" / "TENSOR_CONTRACT.md"
GRAPHS = ["duration.onnx", "decode.onnx"]
VARIANT_TITLES = {
    "micro": "Inflect-Micro-v2",
    "nano": "Inflect-Nano-v2",
}


def fmt_shape(shape) -> str:
    parts = []
    for d in shape:
        if d is None:
            parts.append("?")
        elif isinstance(d, str):
            parts.append(d)  # symbolic dim, e.g. "n_phonemes"
        else:
            parts.append(str(d))
    return "[" + ", ".join(parts) + "]"


def describe(path: Path) -> str:
    lines = [f"## `{path.name}`", ""]

    model = onnx.load(str(path), load_external_data=False)
    opsets = ", ".join(
        f"{o.domain or 'ai.onnx'}={o.version}" for o in model.opset_import
    )
    lines += [
        f"- size: {path.stat().st_size / 1e6:.2f} MB",
        f"- ir_version: {model.ir_version}",
        f"- opset: {opsets}",
        f"- producer: {model.producer_name} {model.producer_version}".rstrip(),
        "",
    ]

    sess = ort.InferenceSession(str(path), providers=["CPUExecutionProvider"])

    for label, tensors in (("Inputs", sess.get_inputs()), ("Outputs", sess.get_outputs())):
        lines += [f"### {label}", "", "| name | dtype | shape |", "| --- | --- | --- |"]
        for t in tensors:
            lines.append(f"| `{t.name}` | `{t.type}` | `{fmt_shape(t.shape)}` |")
        lines.append("")

    # Symbolic dim names are the clearest hint at what each axis means.
    symbolic = sorted(
        {d for t in list(sess.get_inputs()) + list(sess.get_outputs())
         for d in t.shape if isinstance(d, str)}
    )
    if symbolic:
        lines += ["Symbolic dimensions: " + ", ".join(f"`{s}`" for s in symbolic), ""]

    return "\n".join(lines)


def section_for_variant(variant: str, models_root: Path) -> list[str]:
    onnx_dir = models_root / "onnx"
    missing = [g for g in GRAPHS if not (onnx_dir / g).exists()]
    if missing:
        raise SystemExit(
            f"missing graphs {missing} in {onnx_dir} - run scripts/fetch_model.py first"
        )

    config = json.loads((models_root / "config.json").read_text())
    data = config["data"]
    model = config["model"]
    title = VARIANT_TITLES.get(variant, variant)

    doc = [
        f"# {title}",
        "",
        f"Variant id: `{variant}` (assets under `assets/{variant}/`).",
        "",
        "## Audio / text config (`config.json`)",
        "",
        f"- sampling_rate: **{data['sampling_rate']} Hz**, mono",
        f"- hop_length: {data['hop_length']}",
        f"- add_blank: {data['add_blank']} (blank id 0 interleaved between phoneme ids)",
        f"- n_speakers: {data['n_speakers']}",
        f"- inter_channels: {model.get('inter_channels')}",
        f"- use_sdp: {model.get('use_sdp')}",
        "",
    ]
    doc += [describe(onnx_dir / g) for g in GRAPHS]
    return doc


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--model",
        choices=[*VARIANTS, "all"],
        default="all",
        help="which variant to inspect (default: all)",
    )
    ap.add_argument("--models-dir", type=Path, default=MODELS_DIR)
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()

    selected = list(VARIANTS) if args.model == "all" else [args.model]
    parts = [
        "# Inflect v2 ONNX tensor contract",
        "",
        "Generated by `scripts/inspect_graphs.py` - do not edit by hand.",
        "",
        "Both variants share the same I/O names and the shared text frontend; only graph "
        "weights and latent channel counts differ. Kotlin derives `zp_noise` shape from "
        "`duration.onnx` outputs.",
        "",
    ]
    for index, variant in enumerate(selected):
        root = args.models_dir / variant
        if index:
            parts += ["", "---", ""]
        parts += section_for_variant(variant, root)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(parts) + "\n")
    print("\n".join(parts))
    print(f"\nwrote {args.out}")


if __name__ == "__main__":
    main()
